spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1
    username: root
    password: P00j@kum@r!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true